/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.BorderLayout;
import javax.swing.ButtonGroup;

/**
 *
 * @author micha
 */
public class StudentReviewPanel extends javax.swing.JPanel {
    private ButtonGroup ratingGroup = new ButtonGroup();
    private int rating = 0;
    /**
     * Creates new form StudentReviewPanel
     */
    public StudentReviewPanel() {
        initComponents();
        groupButtons();
    }
    
    public void groupButtons() {
        ratingGroup.add(rate1);
        ratingGroup.add(rate2);
        ratingGroup.add(rate3);
        ratingGroup.add(rate4);
        ratingGroup.add(rate5);
    }
    
    
    public void setStudentName(String name) {
        this.applicantNameButton.setText(name);
    }
    
    private void setEditable() {
        this.submitRatingButton.setVisible(false);
        this.rate1.setEnabled(false);
        this.rate2.setEnabled(false);
        this.rate3.setEnabled(false);
        this.rate4.setEnabled(false);
        this.rate5.setEnabled(false);
        
        String recordedRating = this.applicantNameButton.getText() + ": " + rating + " / 5";
        this.applicantNameButton.setText(recordedRating);
        this.applicantNameButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rate1 = new javax.swing.JRadioButton();
        rate3 = new javax.swing.JRadioButton();
        rate2 = new javax.swing.JRadioButton();
        rate4 = new javax.swing.JRadioButton();
        rate5 = new javax.swing.JRadioButton();
        submitRatingButton = new javax.swing.JButton();
        applicantNameButton = new javax.swing.JButton();

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton3.setText("1");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton5.setText("3");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton7.setText("3");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton8.setText("3");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(204, 204, 204));

        rate1.setBackground(new java.awt.Color(204, 204, 204));
        rate1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rate1.setText("1");
        rate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate1ActionPerformed(evt);
            }
        });

        rate3.setBackground(new java.awt.Color(204, 204, 204));
        rate3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rate3.setText("3");
        rate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate3ActionPerformed(evt);
            }
        });

        rate2.setBackground(new java.awt.Color(204, 204, 204));
        rate2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rate2.setText("2");
        rate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate2ActionPerformed(evt);
            }
        });

        rate4.setBackground(new java.awt.Color(204, 204, 204));
        rate4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rate4.setText("4");
        rate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate4ActionPerformed(evt);
            }
        });

        rate5.setBackground(new java.awt.Color(204, 204, 204));
        rate5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rate5.setText("5");
        rate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate5ActionPerformed(evt);
            }
        });

        submitRatingButton.setBackground(new java.awt.Color(0, 0, 51));
        submitRatingButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submitRatingButton.setForeground(new java.awt.Color(255, 255, 255));
        submitRatingButton.setText("Submit Rating");
        submitRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRatingButtonActionPerformed(evt);
            }
        });

        applicantNameButton.setBackground(new java.awt.Color(204, 204, 204));
        applicantNameButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        applicantNameButton.setText("Applicant name:");
        applicantNameButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        applicantNameButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        applicantNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applicantNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(rate1)
                .addGap(29, 29, 29)
                .addComponent(rate2)
                .addGap(29, 29, 29)
                .addComponent(rate3)
                .addGap(26, 26, 26)
                .addComponent(rate4)
                .addGap(27, 27, 27)
                .addComponent(rate5)
                .addGap(27, 27, 27)
                .addComponent(submitRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rate1)
                    .addComponent(rate3)
                    .addComponent(rate2)
                    .addComponent(rate5)
                    .addComponent(rate4)
                    .addComponent(submitRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applicantNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate1ActionPerformed

    private void rate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void rate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void rate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate4ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void rate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate5ActionPerformed

    private void submitRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRatingButtonActionPerformed
        if(this.rate1.isSelected()) {
            this.rating = 1;
            System.out.println("Rating is 1");
	}
	else if(this.rate2.isSelected()) {
            this.rating = 2;
            System.out.println("Rating is 2");
	}
	else if(this.rate3.isSelected()) {
            this.rating = 3;
            System.out.println("Rating is 3");
	}
	else if(this.rate4.isSelected()) {
            this.rating = 4;
            System.out.println("Rating is 4");
	}
	else if(this.rate5.isSelected()) {
            this.rating = 5;
            System.out.println("Rating is 5");
	}
	else {
            this.rating = 0;
            System.out.println("Rating is 0");
	}
        
        setEditable();
    }//GEN-LAST:event_submitRatingButtonActionPerformed

    private void applicantNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantNameButtonActionPerformed
        //Open Up Application
        ApplicationGUI aGUI = new ApplicationGUI(this.applicantNameButton.getText());

    }//GEN-LAST:event_applicantNameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applicantNameButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton rate1;
    private javax.swing.JRadioButton rate2;
    private javax.swing.JRadioButton rate3;
    private javax.swing.JRadioButton rate4;
    private javax.swing.JRadioButton rate5;
    private javax.swing.JButton submitRatingButton;
    // End of variables declaration//GEN-END:variables
}
